personnel/models.py
# coding:utf-8
from decimal import Decimal
from django.db import models
from django.utils.translation import ugettext as _
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Sum

from common.models import CommonModel
from common.models import UnicodeNameMixin
from common.utils import business_days

ABSTRACT_RATIO = Decimal('730.00')
MINIMAL_DAILY_WAGES = Decimal('196.10')
MAXIMUM_DAILY_WAGES = Decimal('1632.87')

INSURANCE_EXPERIENCE_LESS_THAN_FIVE_YEARS = 0
INSURANCE_EXPERIENCE_FROM_FIVE_TO_EIGHT_YEARS = 1
INSURANCE_EXPERIENCE_MORE_THAN_EIGHT_YEARS = 2
INSURANCE_RATIO = {
    INSURANCE_EXPERIENCE_LESS_THAN_FIVE_YEARS: Decimal('0.60'),
    INSURANCE_EXPERIENCE_FROM_FIVE_TO_EIGHT_YEARS: Decimal('0.80'),
    INSURANCE_EXPERIENCE_MORE_THAN_EIGHT_YEARS: Decimal('1.00'),
}

TWOPLACES = Decimal(10) ** -2


class Department(UnicodeNameMixin, CommonModel):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = _(u'отдел')
        verbose_name_plural = _(u'отделы')


class Position(UnicodeNameMixin, CommonModel):
    name = models.CharField(max_length=100)
    wages = models.DecimalField(max_digits=22, decimal_places=2)

    class Meta:
        verbose_name = _(u'должность')
        verbose_name_plural = _(u'должности')


class Employee(UnicodeNameMixin, CommonModel):
    INSURANCE_EXPERIENCE_CHOICES = (
        (INSURANCE_EXPERIENCE_LESS_THAN_FIVE_YEARS, _(u'Менее 5 лет')),
        (INSURANCE_EXPERIENCE_FROM_FIVE_TO_EIGHT_YEARS, _(u'От 5 до 8 лет')),
        (INSURANCE_EXPERIENCE_MORE_THAN_EIGHT_YEARS, _(u'8 лет и более')),
    )

    name = models.CharField(max_length=100)
    department = models.ForeignKey(to=Department)
    position = models.ForeignKey(to=Position)
    personnel_number = models.CharField(unique=True, max_length=100, verbose_name=_(u'табельный номер'))
    permanent_bonus_amount = models.DecimalField(max_digits=22, decimal_places=2)
    insurance_experience = models.SmallIntegerField(
        choices=INSURANCE_EXPERIENCE_CHOICES, default=INSURANCE_EXPERIENCE_LESS_THAN_FIVE_YEARS
    )
    hired = models.DateField()

    class Meta:
        verbose_name = _(u'сотрудник')
        verbose_name_plural = _(u'сотрудники')

    def get_sicktime(self, date):
        return self.sicktime_set.filter(
            start_date__lte=date,
            end_date__gte=date,
            active=True,
        ).first()

    def get_vacation(self, date):
        return self.vacation_set.filter(
            start_date__lte=date,
            end_date__gte=date,
            active=True,
        ).first()

    @property
    def wages(self):
        return self.permanent_bonus_amount + self.position.wages

    @property
    def last_two_years_wages(self):
        return self.wages * Decimal(24)

    @property
    def average_daily_earnings(self):
        return self.wages / Decimal(30)

    def get_bonus_payments(self, month):
        return self.bonus_set.filter(active=True, month=month).aggregate(
            Sum('amount')
        )['amount__sum'] or Decimal()



class Bonus(CommonModel):
    employee = models.ForeignKey(to=Employee)
    month = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(12),
            MinValueValidator(1)
        ]
    )
    year = models.PositiveIntegerField()
    amount = models.DecimalField(max_digits=22, decimal_places=2)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name = _(u'премия')
        verbose_name_plural = _(u'премии')

    @property
    def formatted_date(self, format_=u"{month:0>2}/{year}"):
        return format_.format(month=self.month, year=self.year)

    @property
    def percent(self):
        return (self.amount * Decimal(100)) / self.employee.wages

    def __unicode__(self):
        return u"{name} - {month_year} ({amount})".format(
            name=self.employee.name,
            month_year=self.formatted_date,
            amount=self.amount,
        )


class PaymentsQuerySet(models.QuerySet):
    def get_days_sum(self):
        return sum(map(lambda item: item.days_total, self))

    def get_payments_sum(self):
        return sum(map(lambda item: item.payments, self))


class SickTime(CommonModel):
    employee = models.ForeignKey(to=Employee)
    start_date = models.DateField()
    end_date = models.DateField()
    last_two_years_wages = models.DecimalField(max_digits=22, decimal_places=2)

    class Meta:
        verbose_name = _(u'больничный')
        verbose_name_plural = _(u'больничные')

    def __unicode__(self):
        return u"{name}: {start} - {end}".format(
            name=self.employee.name,
            start=self.start_date,
            end=self.end_date,
        )

    @property
    def day_rate(self):
        insurance_ratio = INSURANCE_RATIO[self.employee.insurance_experience]
        daily_wages = self.last_two_years_wages / ABSTRACT_RATIO
        if daily_wages < MINIMAL_DAILY_WAGES:
            daily_wages = MINIMAL_DAILY_WAGES
        if daily_wages > MAXIMUM_DAILY_WAGES:
            daily_wages = MAXIMUM_DAILY_WAGES
        return daily_wages * insurance_ratio


class Vacation(CommonModel):
    employee = models.ForeignKey(to=Employee)
    start_date = models.DateField()
    end_date = models.DateField()
    average_daily_earnings = models.DecimalField(max_digits=22, decimal_places=2)

    class Meta:
        verbose_name = _(u'отпуск')
        verbose_name_plural = _(u'отпуска')


    def __unicode__(self):
        return u"{name}: {start} - {end}".format(
            name=self.employee.name,
            start=self.start_date,
            end=self.end_date,
        )

    @property
    def day_rate(self):
        return self.average_daily_earnings

personnel/forms.py
# coding:utf-8
from decimal import Decimal

from django import forms
from django.forms.models import ModelForm
from django.utils.translation import ugettext as _
from django.core.exceptions import ValidationError

from personnel.models import (
    Department,
    Employee,
    Position,
    Bonus,
    SickTime,
    Vacation,
)
from common.mixins import CleanMonthYearMixin
from common.forms import CleanStartEndMixin


class PersonnelForm(ModelForm):
    class Meta:
        exclude = (
            'active',
            'created_date',
            'updated_date',
            'created_by',
            'updated_by',
        )

    class Media:
        js = (
            'assets/js/bootstrap-inputmask/bootstrap-inputmask.min.js',
            'assets/js/form-component.js',
        )


class DepartmentForm(PersonnelForm):
    class Meta(PersonnelForm.Meta):
        model = Department
        labels = {
            'name': _(u'Название отдела'),
        }


class EmployeeForm(PersonnelForm):
    hired = forms.DateField(
        widget=forms.DateInput(attrs={
                'data-provide': 'datepicker',
                'data-date-language': 'ru',
                'data-date-format': 'dd.mm.yyyy',
        }),
        label=_(u'Дата приема на работу'),
    )

    class Meta(PersonnelForm.Meta):
        model = Employee
        labels = {
            'name': _(u'Фамилия, Имя, Отчество'),
            'department': _(u'Отдел'),
            'position': _(u'Должность'),
            'personnel_number': _(u'Табельный номер'),
            'permanent_bonus_amount': _(u'Постоянная премия'),
            'insurance_experience': _(u'Страховой стаж'),
        }

    class Media:
        css = {
            'all': ('assets/css/bootstrap-datepicker3.min.css',),
        }
        js = (
            'assets/js/bootstrap-datepicker.min.js',
            'assets/locales/bootstrap-datepicker.ru.min.js',
        )


class PositionForm(PersonnelForm):
    class Meta(PersonnelForm.Meta):
        model = Position
        labels = {
            'name': _(u'Название'),
            'wages': _(u'Ставка'),
        }


class BonusForm(CleanMonthYearMixin, PersonnelForm):
    percent = forms.FloatField(
        required=False,
        min_value=0,
        label=_(u'Процент от заработной платы'),
        help_text=_(u'Введите процентное соотношение размера премии к заработной плате '
            u'сотрудника.'),
    )
    month_year = forms.CharField(
        widget=forms.DateInput(attrs={
                'data-provide': 'datepicker',
                'data-date-format': 'mm/yyyy',
                'data-date-language': 'ru',
                'data-date-min-view-mode': 'months',
        }, format=('%m/%Y')),
        label=_(u'За месяц'),
    )

    class Meta(PersonnelForm.Meta):
        model = Bonus
        fields = (
            'employee',
            'month_year',
            'percent',
            'amount',
            'description',
        )
        labels = {
            'amount': _(u'Сумма'),
            'description': _(u'Описание'),
        }

    class Media:
        css = {
            'all': ('assets/css/bootstrap-datepicker3.min.css',),
        }
        js = (
            'assets/js/bootstrap-datepicker.min.js',
            'assets/locales/bootstrap-datepicker.ru.min.js',
        )

    def __init__(self, *args, **kwargs):
        super(BonusForm, self).__init__(*args, **kwargs)
        if self.instance.pk:
            self.initial['month_year'] = "{month:0>2d}/{year}".format(
                month=self.instance.month,
                year=self.instance.year
            )

    def save(self, commit=True):
        instance = super(BonusForm, self).save(commit=False)
        instance.month, instance.year = self.cleaned_data['month_year']
        if commit:
            instance.save()
        return instance


class BonusCreateForm(BonusForm):
    employee = forms.ModelChoiceField(
        queryset=Employee.objects.filter(active=True),
        label=_(u'Сотрудник'),
    )

    class Meta(BonusForm.Meta):
        exclude = (
            'amount',
        )

    def save(self, commit=True):
        instance = super(BonusCreateForm, self).save(commit=False)
        instance.amount = instance.employee.wages * Decimal(self.cleaned_data['percent'] / 100.0)
        if commit:
            instance.save()
        return instance


class BonusUpdateForm(BonusForm):
    class Meta(BonusForm.Meta):
        exclude = BonusForm.Meta.exclude + (
            'employee',
        )


class SickTimeForm(CleanStartEndMixin, PersonnelForm):
    start_date = forms.DateField(
        widget=forms.DateInput(attrs={
                'data-provide': 'datepicker',
                'data-date-language': 'ru',
                'data-date-format': 'dd.mm.yyyy',
        }),
        label=_(u'Начало'),
    )
    end_date = forms.DateField(
        widget=forms.DateInput(attrs={
                'data-provide': 'datepicker',
                'data-date-language': 'ru',
                'data-date-format': 'dd.mm.yyyy',
        }),
        label=_(u'Окончание'),
    )

    class Meta(PersonnelForm.Meta):
        model = SickTime
        labels = {
            'last_two_years_wages': _(u'Суммарный заработок за последние 24 месяца'),
        }
        help_texts = {
            'last_two_years_wages': _(u'Укажите фактический суммарный ежемесячный заработок сотрудника '
                u'за последние 24 месяца. Необходимы все выплаты, на которые начислены страховые взносы в ФСС. '
                u'К таким выплатам не относятся больничные, пособия за счет ФСС и другие выплаты '
                u'в соответствии со ст.9 212-ФЗ.'
            )
        }

    class Media:
        css = {
            'all': ('assets/css/bootstrap-datepicker3.min.css',),
        }
        js = (
            'assets/js/bootstrap-datepicker.min.js',
            'assets/locales/bootstrap-datepicker.ru.min.js',
        )


class SickTimeCreateForm(SickTimeForm):
    employee = forms.ModelChoiceField(
        queryset=Employee.objects.filter(active=True),
        label=_(u'Сотрудник'),
    )


class SickTimeUpdateForm(SickTimeForm):
    class Meta(SickTimeForm.Meta):
        exclude = SickTimeForm.Meta.exclude + (
            'employee',
        )


class VacationForm(CleanStartEndMixin, PersonnelForm):
    start_date = forms.DateField(
        widget=forms.DateInput(attrs={
                'data-provide': 'datepicker',
                'data-date-language': 'ru',
                'data-date-format': 'dd.mm.yyyy',
        }),
        label=_(u'Начало'),
    )

    end_date = forms.DateField(
        widget=forms.DateInput(attrs={
                'data-provide': 'datepicker',
                'data-date-language': 'ru',
                'data-date-format': 'dd.mm.yyyy',
        }),
        label=_(u'Окончание'),
    )

    class Meta(PersonnelForm.Meta):
        model = Vacation
        labels = {
            'average_daily_earnings': _(u'Среднедневной заработок'),
        }
        help_texts = {
                'average_daily_earnings': _(u'Средний дневной заработок по всем начислениям за расчетный период '
                    u'кроме следующих: '
                    u'больничные, отпуска, пособия до полутора лет, оплата по среднему заработку, '
                    u'и др. начисления в соответствии с п.5 Постановления Правительства РФ №922 от 24.12.2007г.;'
                ),
        }

    class Media:
        css = {
            'all': ('assets/css/bootstrap-datepicker3.min.css',),
        }
        js = (
            'assets/js/bootstrap-datepicker.min.js',
            'assets/locales/bootstrap-datepicker.ru.min.js',
        )


class VacationCreateForm(VacationForm):
    employee = forms.ModelChoiceField(
        queryset=Employee.objects.filter(active=True),
        label=_(u'Сотрудник'),
    )


class VacationUpdateForm(VacationForm):
    class Meta(VacationForm.Meta):
        exclude = VacationForm.Meta.exclude + (
            'employee',
        )

personnel/templates/personnel/bonus_confirm_delete.html
{% extends 'confirm.html' %}
{% load i18n %}

{% block nav-bonuses %}
<li class="sub-menu">
    <a href="{% url 'bonus-list' %}" class="active">
    <i class="fa fa-usd"></i>
    <span>{% trans 'Премии' %}</span>
    </a>
</li>
{% endblock %}

{% block title %}
    <h3><i class="fa fa-usd"></i> {% trans 'Удалить' %} {{ object }}?</h3>
{% endblock %}

personnel/templates/personnel/bonus_form.html
{% extends 'form.html' %}
{% load i18n %}

{% block nav-bonuses %}
<li class="sub-menu">
    <a href="{% url 'bonus-list' %}" class="active">
    <i class="fa fa-usd"></i>
    <span>{% trans 'Премии' %}</span>
    </a>
</li>
{% endblock %}

{% block title %}
{% if form.instance.pk %}
<h3><i class="fa fa-usd"></i> {{ form.instance }}</h3>
{% else %}
<h3><i class="fa fa-usd"></i> {% trans 'Новая премия' %}</h3>
{% endif %}
{% endblock %}

{% block buttons %}
{{ block.super }}
{% if object.pk %}
<a class="btn btn-danger" href="{% url 'bonus-delete' object.pk %}">{% trans 'Удалить' %}</a>
{% endif %}
{% endblock %}

{% block js %}
{{ block.super }}
<script>
    var wages = parseFloat({{ form.instance.employee.wages }});
    $("#id_percent").on("change keyup", function(evt) {
        var amount = (parseFloat($(this).val()) * wages) / 100.0;
        $("#id_amount").val(amount.toFixed(2));
    });
    $("#id_amount").on("change keyup", function(evt) {
        var percent = (parseFloat($(this).val()) * 100.0) / wages;
        $("#id_percent").val(percent);
    });
</script>
{% endblock %}

personnel/templates/personnel/bonus_list.html
{% extends 'table.html' %}
{% load i18n %}

{% block nav-bonuses %}
<li class="sub-menu">
    <a href="{% url 'bonus-list' %}" class="active">
    <i class="fa fa-usd"></i>
    <span>{% trans 'Премии' %}</span>
    </a>
</li>
{% endblock %}

{% block title %}
    <h3><i class="fa fa-usd"></i> {% trans 'Премии' %}</h3>
{% endblock %}

{% block table-head %}
<th><i class="fa fa-user"></i> {% trans 'Фамилия, Имя, Отчество' %}</th>
<th><i class="fa fa-calendar"></i> {% trans 'Месяц' %}</th>
<th><i class="fa fa-usd"></i> {% trans 'Сумма' %}</th>
<th></th>
{% endblock %}

{% block table-body %}
{% for object in object_list %}
<tr>
    {% if object.employee.active %}
    <td>{{ object.employee }}</td>
    {% else %}
    <td><strike>{{ object.employee }}</strike></td>
    {% endif %}
    <td>{{ object.formatted_date }}</td>
    <td>{{ object.amount }}</td>
    <td>
        {% if object.employee.active %}
        <a class="btn btn-primary btn-xs" href="{% url 'bonus-update' object.pk %}"><i class="fa fa-pencil"></i></a>
        {% endif %}
        <a class="btn btn-danger btn-xs" href="{% url 'bonus-delete' object.pk %}"><i class="fa fa-trash-o "></i></a>
    </td>
</tr>
{% endfor %}
{% endblock %}

{% block content-footer %}
{% if not object_list %}
<div class="alert alert-warning">
    {% trans 'Не найдено ни одний премии' %}
</div>
{% endif %}
{% endblock %}

{% block buttons %}
    <a class="btn btn-success btn-sm pull-left" href="{% url 'bonus-create' %}"> {% trans 'Добавить премию' %}</a>
{% endblock %}

personnel/templates/personnel/department_list.html
{% extends 'list.html' %}
{% load i18n %}

{% block nav-departments %}
<li class="sub-menu">
    <a href="{% url 'department-list' %}" class="active">
    <i class="fa fa-users"></i>
    <span>{% trans 'Отделы' %}</span>
    </a>
</li>
{% endblock %}

{% block title %}
    <h3><i class="fa fa-users"></i> {% trans 'Список отделов' %}</h3>
{% endblock %}

{% block items %}
{% for object in object_list %}
    <li>
        <div class="task-title">
            <span class="task-title-sp"><a href="{% url 'employee-list' object.pk %}">{{ object }}</a></span>
            <div class="pull-right hidden-phone">
                <a class="btn btn-primary btn-xs" href="{% url 'department-update' object.pk %}"><i class="fa fa-pencil"></i></a>
                <a class="btn btn-danger btn-xs" href="{% url 'department-delete' object.pk %}"><i class="fa fa-trash-o"></i></a>
            </div>
        </div>
    </li>
{% endfor %}
{% endblock %}

{% block content-footer %}
{% if not object_list %}
<div class="alert alert-warning">
    {% trans 'Не найдено ни одного отдела' %}
</div>
{% endif %}
{% endblock %}

{% block add-button %}
    <a class="btn btn-success btn-sm pull-left" href="{% url 'department-create' %}"> {% trans 'Добавить отдел' %}</a>
{% endblock %}

personnel/templates/personnel/employee_form.html
{% extends 'form.html' %}
{% load i18n %}

{% block nav-departments %}
<li class="sub-menu">
    <a href="{% url 'department-list' %}" class="active">
    <i class="fa fa-users"></i>
    <span>{% trans 'Отделы' %}</span>
    </a>
</li>
{% endblock %}

{% block title %}
{% if form.instance.pk %}
<h3><i class="fa fa-user"></i> <a href="{% url 'employee-list' form.initial.department.pk %}">{{ form.initial.department }}</a> <i class="fa fa-angle-right"></i> {{ form.instance.name }}</h3>
{% else %}
<h3><i class="fa fa-user"></i> <a href="{% url 'employee-list' form.initial.department.pk %}">{{ form.initial.department }}</a> <i class="fa fa-angle-right"></i> {% trans 'Новый сотрудник' %} </h3>
{% endif %}
{% endblock %}

{% block buttons %}
{{ block.super }}
{% if object.pk %}
<a class="btn btn-danger" href="{% url 'employee-delete' object.pk %}">{% trans 'Удалить' %}</a>
{% endif %}
{% endblock %}

personnel/templates/personnel/position_confirm_delete.html
{% extends 'confirm.html' %}
{% load i18n %}

{% block nav-positions %}
<li class="sub-menu">
    <a href="{% url 'position-list' %}" class="active">
    <i class="fa fa-star"></i>
    <span>{% trans 'Должности' %}</span>
    </a>
</li>
{% endblock %}

{% block title %}
    <h3><i class="fa fa-star"></i> {% trans 'Удалить' %} {{ object }}?</h3>
{% endblock %}

personnel/templates/personnel/position_form.html
{% extends 'form.html' %}
{% load i18n %}

{% block nav-positions %}
<li class="sub-menu">
    <a href="{% url 'position-list' %}" class="active">
    <i class="fa fa-star"></i>
    <span>{% trans 'Должности' %}</span>
    </a>
</li>
{% endblock %}

{% block title %}
{% if form.instance.pk %}
<h3><i class="fa fa-star"></i> {{ form.instance.name }}</h3>
{% else %}
<h3><i class="fa fa-star"></i> {% trans 'Новая должность' %}</h3>
{% endif %}
{% endblock %}

{% block buttons %}
{{ block.super }}
{% if object.pk %}
<a class="btn btn-danger" href="{% url 'position-delete' object.pk %}">{% trans 'Удалить' %}</a>
{% endif %}
{% endblock %}

personnel/templates/personnel/sicktime_confirm_delete.html
{% extends 'confirm.html' %}
{% load i18n %}

{% block nav-sicktimes %}
<li class="sub-menu">
    <a href="{% url 'sicktime-list' %}" class="active">
    <i class="fa fa-heart"></i>
    <span>{% trans 'Больничные' %}</span>
    </a>
</li>
{% endblock %}

{% block title %}
    <h3><i class="fa fa-heart"></i> {% trans 'Удалить' %} {{ object }}?</h3>
{% endblock %}

personnel/templates/personnel/sicktime_form.html
{% extends 'form.html' %}
{% load i18n %}

{% block nav-sicktimes %}
<li class="sub-menu">
    <a href="{% url 'sicktime-list' %}" class="active">
    <i class="fa fa-heart"></i>
    <span>{% trans 'Больничные' %}</span>
    </a>
</li>
{% endblock %}

{% block title %}
{% if form.instance.pk %}
<h3><i class="fa fa-heart"></i> {{ form.instance }}</h3>
{% else %}
<h3><i class="fa fa-heart"></i> {% trans 'Новый больничный' %}</h3>
{% endif %}
{% endblock %}

{% block buttons %}
{{ block.super }}
{% if object.pk %}
<a class="btn btn-danger" href="{% url 'sicktime-delete' object.pk %}">{% trans 'Удалить' %}</a>
{% endif %}
{% endblock %}

personnel/templates/personnel/sicktime_list.html
{% extends 'table.html' %}
{% load i18n %}

{% block nav-sicktimes %}
<li class="sub-menu">
    <a href="{% url 'sicktime-list' %}" class="active">
    <i class="fa fa-heart"></i>
    <span>{% trans 'Больничные' %}</span>
    </a>
</li>
{% endblock %}

{% block title %}
    <h3><i class="fa fa-heart"></i> {% trans 'Больничные' %}</h3>
{% endblock %}

{% block table-head %}
<th><i class="fa fa-user"></i> {% trans 'Фамилия, Имя, Отчество' %}</th>
<th><i class="fa fa-calendar"></i> {% trans 'Начало' %}</th>
<th><i class="fa fa-calendar"></i> {% trans 'Окончание' %}</th>
<th></th>
{% endblock %}

{% block table-body %}
{% for object in object_list %}
<tr>
    {% if object.employee.active %}
    <td>{{ object.employee }}</td>
    {% else %}
    <td><strike>{{ object.employee }}</strike></td>
    {% endif %}
    <td>{{ object.start_date }}</td>
    <td>{{ object.end_date }}</td>
    <td>
        {% if object.employee.active %}
        <a class="btn btn-primary btn-xs" href="{% url 'sicktime-update' object.pk %}"><i class="fa fa-pencil"></i></a>
        {% endif %}
        <a class="btn btn-danger btn-xs" href="{% url 'sicktime-delete' object.pk %}"><i class="fa fa-trash-o "></i></a>
    </td>
</tr>
{% endfor %}
{% endblock %}

{% block content-footer %}
{% if not object_list %}
<div class="alert alert-warning">
    {% trans 'Не найдено ни одного больничного' %}
</div>
{% endif %}
{% endblock %}

{% block buttons %}
    <a class="btn btn-success btn-sm pull-left" href="{% url 'sicktime-create' %}"> {% trans 'Добавить больничный' %}</a>
{% endblock %}

personnel/templates/personnel/vacation_confirm_delete.html
{% extends 'confirm.html' %}
{% load i18n %}

{% block nav-vacations %}
<li class="sub-menu">
    <a href="{% url 'vacation-list' %}" class="active">
    <i class="fa fa-car"></i>
    <span>{% trans 'Отпуска' %}</span>
    </a>
</li>
{% endblock %}

{% block title %}
    <h3><i class="fa fa-car"></i> {% trans 'Удалить' %} {{ object }}?</h3>
{% endblock %}

personnel/templates/personnel/vacation_create_form.html
{% extends 'personnel/vacation_form.html' %}

{% block js %}
{{ block.super }}
<script>
    var employeesAverageDailyEarnings = {{ employees_average_daily_earnings|safe }};
    $("#id_employee").change(function() {
        $("#id_average_daily_earnings").val(
            employeesAverageDailyEarnings[$(this).val()] || ""
        )
    });
</script>
{% endblock %}

personnel/templates/personnel/vacation_form.html
{% extends 'form.html' %}
{% load i18n %}

{% block nav-vacations %}
<li class="sub-menu">
    <a href="{% url 'vacation-list' %}" class="active">
    <i class="fa fa-car"></i>
    <span>{% trans 'Отпуска' %}</span>
    </a>
</li>
{% endblock %}

{% block title %}
{% if form.instance.pk %}
<h3><i class="fa fa-car"></i> {{ form.instance }}</h3>
{% else %}
<h3><i class="fa fa-car"></i> {% trans 'Новый отпуск' %}</h3>
{% endif %}
{% endblock %}

{% block buttons %}
{{ block.super }}
{% if object.pk %}
<a class="btn btn-danger" href="{% url 'vacation-delete' object.pk %}">{% trans 'Удалить' %}</a>
{% endif %}
{% endblock %}

personnel/templates/personnel/vacation_list.html
{% extends 'table.html' %}
{% load i18n %}

{% block nav-vacations %}
<li class="sub-menu">
    <a href="{% url 'vacation-list' %}" class="active">
    <i class="fa fa-car"></i>
    <span>{% trans 'Отпуска' %}</span>
    </a>
</li>
{% endblock %}

{% block title %}
    <h3><i class="fa fa-car"></i> {% trans 'Отпуска' %}</h3>
{% endblock %}

{% block table-head %}
<th><i class="fa fa-user"></i> {% trans 'Фамилия, Имя, Отчество' %}</th>
<th><i class="fa fa-calendar"></i> {% trans 'Начало' %}</th>
<th><i class="fa fa-calendar"></i> {% trans 'Окончание' %}</th>
<th></th>
{% endblock %}

{% block table-body %}
{% for object in object_list %}
<tr>
    {% if object.employee.active %}
    <td>{{ object.employee }}</td>
    {% else %}
    <td><strike>{{ object.employee }}</strike></td>
    {% endif %}
    <td>{{ object.start_date }}</td>
    <td>{{ object.end_date }}</td>
    <td>
        {% if object.employee.active %}
        <a class="btn btn-primary btn-xs" href="{% url 'vacation-update' object.pk %}"><i class="fa fa-pencil"></i></a>
        {% endif %}
        <a class="btn btn-danger btn-xs" href="{% url 'vacation-delete' object.pk %}"><i class="fa fa-trash-o "></i></a>
    </td>
</tr>
{% endfor %}
{% endblock %}

{% block content-footer %}
{% if not object_list %}
<div class="alert alert-warning">
    {% trans 'Не найдено ни одного отпуска' %}
</div>
{% endif %}
{% endblock %}

{% block buttons %}
    <a class="btn btn-success btn-sm pull-left" href="{% url 'vacation-create' %}"> {% trans 'Добавить отпуск' %}</a>
{% endblock %}